language: python
sudo: false
dist: trusty
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x

matrix:
  include:
## PYTHON 3.8
    - python: '3.9'
      dist: bionic
      sudo: true
      env:
        - TOXENV=.python39
## PYTHON 3.8
    - python: '3.8'
      dist: bionic
      sudo: true
      env:
        - TOXENV=.python38
## PYTHON 3.7
    - python: '3.7'
      dist: xenial
      sudo: true
      env:
        - TOXENV=.python37
## PYTHON 3.6
    - python: '3.6'
      env:
        - TOXENV=.python36
## PYTHON 3.6 - OTHER TESTS
    - python: '3.8'
      dist: bionic
      sudo: true
      env:
        - TOXENV=docs
    - python: '3.8'
      dist: bionic
      sudo: true
      env:
        - TOXENV=coverage

install:
  - pip install -U tox codecov

script:
  - tox -- -nauto -v

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
